using Dsw2026Tpi.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Dsw2026Tpi.Data.Configurations;

public class AvailabilityRuleConfiguration
    : IEntityTypeConfiguration<AvailabilityRule>
{
    public void Configure(
        EntityTypeBuilder<AvailabilityRule> builder)
    {
        builder.ToTable("AvailabilityRules");
        builder.HasKey(rule => rule.Id);

        builder.Property(rule => rule.Id)
            .ValueGeneratedNever(); // The Id is generated by the application, not the database.

        builder.Property(rule => rule.DoctorId)
            .IsRequired();

        builder.Property(rule => rule.Month)
            .HasColumnType("tinyint")
            .IsRequired();

        builder.Property(rule => rule.Year)
            .HasColumnType("smallint")
            .IsRequired();

        builder.Property(rule => rule.DayOfWeek)
            .HasConversion<byte>()
            .HasColumnType("tinyint")
            .IsRequired();

        builder.Property(rule => rule.StartTime)
            .HasColumnType("time(0)")
            .IsRequired();

        builder.Property(rule => rule.EndTime)
            .HasColumnType("time(0)")
            .IsRequired();

        builder.Property(rule => rule.Deleted)
            .IsRequired()
            .HasDefaultValue(false);

        builder.HasIndex(rule => new
            {
                rule.DoctorId,
                rule.Year,
                rule.Month,
                rule.DayOfWeek,
                rule.StartTime,
                rule.EndTime
            })
            .IsUnique()
            .HasDatabaseName(
                "UX_AvailabilityRules_Doctor_Month_Day_Time")
            .HasFilter("[Deleted] = 0");

        builder.HasQueryFilter(
            rule => !rule.Deleted);

        builder.HasOne(rule => rule.Doctor)
            .WithMany(doctor =>
                doctor.AvailabilityRules)
            .HasForeignKey(rule => rule.DoctorId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
